import type { Metadata } from "next";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg-special-800 text-special-50'>
        {children}
      </body>
    </html>
  );
}
